name = "h5part-c"
version = "1.0.0"
maintainer = "左志华(zuo.zhihua@qq.com)"
license = "BSD-3-Clause"

[library]
include-dir = ["include"]

[build]
link = ["hdf5", "hdf5_hl"]

[[example]]
name = "demo"
main = "demo.c"
