name = "h5part-c"
version = "1.0.0"
maintainer = "ZUO Zhihua(zuo.zhihua@qq.com)"
license = "BSD-3-Clause"

[library]
include-dir = ["include"]

[build]
link = ['hdf5']

[[example]]
name = "demo"
main = "demo.c"
